name: "Dependency Review"
on:
  pull_request:
  merge_group:
permissions: read-all
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          base-ref: ${{ github.base_ref || github.event.merge_group.base_ref }}
          head-ref: ${{ github.head_ref || github.event.merge_group.head_ref }}
